/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.awt.AWTException;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import recordscreenshot.RecordScreenshot;

/**
 *
 * @author hp
 */
public class FullSc extends javax.swing.JFrame {

    /**
     * Creates new form FullSc
     */
    public FullSc() {
        setUndecorated(true);
        
        initComponents();
        setExtendedState(this.MAXIMIZED_BOTH);
         fullScImg.setOpaque(false);
         x = y = x2 = y2 = 0; //
         takingShot();
         Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
//         System.out.println("width:"+screenSize.width+"Hight"+screenSize.height);

//         System.out.println("width"+fullScImg.getSize().getWidth()+"Hight"+fullScImg.getSize().getHeight());
         imgLbl.setIcon(new ImageIcon(new ImageIcon("fullScreen.png").getImage().getScaledInstance(fullScImg.getWidth(), fullScImg.getHeight(), Image.SCALE_SMOOTH)));
                  imgLbl.setSize((int)screenSize.getWidth(), (int)screenSize.getHeight());
//                  System.out.println("width"+imgLbl.getWidth()+"Hight"+imgLbl.getHeight());
//this.setState(0);

    }
    int x, y, x2, y2;
    
    
    public static FullSc area=null;
     public static FullSc getObj(){
        if(area==null){
            area=new FullSc();
        }
        return area;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fullScImg = new javax.swing.JPanel();
        imgLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        fullScImg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                fullScImgMouseDragged(evt);
            }
        });
        fullScImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fullScImgMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fullScImgMouseReleased(evt);
            }
        });

        imgLbl.setPreferredSize(new java.awt.Dimension(1366, 768));

        javax.swing.GroupLayout fullScImgLayout = new javax.swing.GroupLayout(fullScImg);
        fullScImg.setLayout(fullScImgLayout);
        fullScImgLayout.setHorizontalGroup(
            fullScImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fullScImgLayout.createSequentialGroup()
                .addComponent(imgLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        fullScImgLayout.setVerticalGroup(
            fullScImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fullScImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fullScImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            try {
                //installing Jtatto theme
                UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
                

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(RecordScreenshot.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(RecordScreenshot.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(RecordScreenshot.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(RecordScreenshot.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        }
//           MainUI mu=new MainUI();
//           mu.setAlwaysOnTop(true);
    }//GEN-LAST:event_formWindowClosing

    private void fullScImgMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullScImgMouseReleased
        // TODO add your handling code here:
        setEndPoint(evt.getX(), evt.getY());
        repaint();
        
        PopUpDemo menu = new PopUpDemo();
        menu.show(fullScImg, x2, y2);

    }//GEN-LAST:event_fullScImgMouseReleased

    private void fullScImgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullScImgMousePressed
        // TODO add your handling code here:
        setStartPoint(evt.getX(), evt.getY());
        //        x=evt.getX();
        //        y=evt.getY();
    }//GEN-LAST:event_fullScImgMousePressed

    private void fullScImgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullScImgMouseDragged
        // TODO add your handling code here:
        setEndPoint(evt.getX(), evt.getY());
        repaint();
    }//GEN-LAST:event_fullScImgMouseDragged

     public void setStartPoint(int x, int y) {
            this.x = x;
            this.y = y;
//            System.out.println("X:"+x+" Y:"+y);
        }

        public void setEndPoint(int x, int y) {
            x2 = (x);
            y2 = (y);
//            System.out.println("X:"+x2+" Y:"+y2);
        }

        public void drawPerfectRect(Graphics g, int x, int y, int x2, int y2) {
            int px = Math.min(x,x2);
            int py = Math.min(y,y2);
            int pw=Math.abs(x-x2);
            int ph=Math.abs(y-y2);
            g.setColor(Color.RED);
            g.drawRect(px, py, pw, ph);
        }

        ///////////////
//         void drawRectangles(Graphics g) {
//        Graphics2D g2d = (Graphics2D) g;
//        	g2d.setColor(Color.RED);
////        g2d.fillRect(x, y, x2, y2);
//        g2d.drawRect(x, y, x2, y2); 
//        
//    }
 
    @Override
    public void paint(Graphics g) {
        super.paint(g);
//        drawRectangles(g);
        drawPerfectRect(g, x, y, x2, y2);
    }
    
    public void capture(){
        try {
            int px = Math.min(x,x2);
            int py = Math.min(y,y2);
            int pw=Math.abs(x-x2);
            int ph=Math.abs(y-y2);
            Robot robot = new Robot();
            
            Rectangle rectangle = new Rectangle(px, py, pw, ph);
            BufferedImage bufferedImage = robot.createScreenCapture(rectangle);
            File file = new File("testing.png");           
            boolean status = ImageIO.write(bufferedImage, "png", file);
            if(status==true){
            }
        } catch (AWTException ex) {
            Logger.getLogger(FullSc.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FullSc.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }
    
    public void takingShot(){
        try{
            
            Robot robot = new Robot();
 
            Rectangle rectangle = new Rectangle(Toolkit.getDefaultToolkit().getScreenSize());
            BufferedImage bufferedImage = robot.createScreenCapture(rectangle);
            File file = new File("fullScreen.png");           
            boolean status = ImageIO.write(bufferedImage, "png", file);
            
//            MainUI.shotName=MainUI.shotName+1; //increase shot name counter
//            isFileSaved=false; //marked as there's unsaved data
        }catch(AWTException  | IOException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
   
 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FullSc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FullSc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FullSc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FullSc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FullSc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fullScImg;
    private javax.swing.JLabel imgLbl;
    // End of variables declaration//GEN-END:variables
}

class PopUpDemo extends JPopupMenu {
    public PopUpDemo() {
        JMenuItem save = new JMenuItem("Save");
        JMenuItem reCapture = new JMenuItem("Recapture");
        JMenuItem cancel = new JMenuItem("Cancel");
        JMenuItem email = new JMenuItem("Send By E-mail");
        add(save);
        add(reCapture);
        add(cancel);
        add(email);
    }
}
