/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imageViewer;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import recordscreenshot.StoringCommShots;
import frames.MainUI;
import java.awt.FileDialog;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Salah
 */
public class ImgView extends javax.swing.JFrame {

    int pagesNO;
    public static ImgView iv=null;
    /**
     * Creates new form ImgView
     */
    public ImgView() {     
        initComponents();
        //check if there're no screenshots show message only
        if(getNoShots()==0){
            JOptionPane.showMessageDialog(null, "There're no added images to preview");
            WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
            Toolkit.getDefaultToolkit().getSystemEve­ntQueue().postEvent(winClosingEvent);

        }else{
            //open the first image
            settingIco(StoringCommShots.arr[0][0]);
            comments.setText(StoringCommShots.arr[1][0]);//get the first comment
            currPage.setText("1"); //set current page
        }

        if(noOpages.getText().equals(currPage.getText())){
            nxtbtn.setEnabled(false); //if there's only one screenshot lock the navigation
        }
        bkBtn.setEnabled(false);//disable nvigate back button
        this.setLocationRelativeTo(null);
    }

    
     public static ImgView getObj(){
        if(iv==null){
            iv=new ImgView();
        }
        return iv;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        imgPreviewLbl = new javax.swing.JLabel();
        saveAsbtn = new javax.swing.JButton();
        nxtbtn = new javax.swing.JButton();
        bkBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        noOpages = new javax.swing.JLabel();
        currPage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        comments = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Preview Screenshots");
        setPreferredSize(new java.awt.Dimension(1265, 603));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        saveAsbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/floppy_disk_edit.png"))); // NOI18N
        saveAsbtn.setText("Save as");
        saveAsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsbtnActionPerformed(evt);
            }
        });

        nxtbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrow_right_blue.png"))); // NOI18N
        nxtbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxtbtnActionPerformed(evt);
            }
        });

        bkBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrow_left_blue.png"))); // NOI18N
        bkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkBtnActionPerformed(evt);
            }
        });

        delBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        delBtn.setText("Delete");
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        noOpages.setText("jLabel2");

        currPage.setText("jLabel1");

        jLabel1.setText("of");

        comments.setColumns(20);
        comments.setRows(5);
        jScrollPane2.setViewportView(comments);

        jLabel2.setText("Comments");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/floppy_disk_ok.png"))); // NOI18N
        jButton2.setText("update comments");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(imgPreviewLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(currPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noOpages)
                        .addGap(32, 32, 32)
                        .addComponent(bkBtn))
                    .addComponent(saveAsbtn))
                .addGap(18, 18, 18)
                .addComponent(nxtbtn)
                .addGap(100, 100, 100)
                .addComponent(delBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(imgPreviewLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(noOpages)
                            .addComponent(currPage)
                            .addComponent(jLabel1)
                            .addComponent(bkBtn)
                            .addComponent(nxtbtn)
                            .addComponent(delBtn))
                        .addGap(18, 18, 18)
                        .addComponent(saveAsbtn))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        jScrollPane1.setViewportView(jPanel1);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Update comments");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Delete");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1049, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveAsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsbtnActionPerformed
        //copy the selected image to the selected location
        FileDialog fDialog = new FileDialog(this,"Save", FileDialog.SAVE);
        fDialog.setFile("Screenshot");
        fDialog.setVisible(true);
        
        String fileName=fDialog.getFile();
        if(fileName.contains(".")){
            JOptionPane.showMessageDialog(null, "you can't insert '.' in File Name");
        }else{
            String dir = fDialog.getDirectory();
            String path=dir+fileName;
//            System.out.println("Path is:"+path);
            copyPasteImg(StoringCommShots.arr[0][Integer.parseInt(currPage.getText())-1], path+".png");
        }
        
    }//GEN-LAST:event_saveAsbtnActionPerformed

    private void nxtbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxtbtnActionPerformed
        // TODO add your handling code here:
        next();
    }//GEN-LAST:event_nxtbtnActionPerformed

    private void bkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkBtnActionPerformed
        // TODO add your handling code here:
        bk();
        
    }//GEN-LAST:event_bkBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        // TODO add your handling code here:
        delete();

        
    }//GEN-LAST:event_delBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        saveComments();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        ImgView.iv=null;
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        saveComments();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**Delete screenshot and its comment then shift the array*/
    public void delete(){
        StoringCommShots cs=new StoringCommShots();
        File img=new File(StoringCommShots.arr[0][Integer.parseInt(currPage.getText())-1]);
        
        if(noOpages.getText().equals("1")){
            WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
            Toolkit.getDefaultToolkit().getSystemEve­ntQueue().postEvent(winClosingEvent);
            img.delete();
            StoringCommShots.arr[0][0]=null;
            StoringCommShots.arr[1][0]=null;
            ImgView.iv=null;
            
        }else{
            img.delete();
            
            //shifting array after delete
            int currPageindex=Integer.parseInt(currPage.getText())-1;
            int lastIndex=cs.getLastIndex();
            
            if(currPageindex==lastIndex){
                StoringCommShots.arr[0][lastIndex]=null;
                StoringCommShots.arr[1][lastIndex]=null;
            }else{
                for(int i=Integer.parseInt(currPage.getText())-1;i<199;i++){
                    StoringCommShots.arr[0][i]=StoringCommShots.arr[0][i+1];
                    StoringCommShots.arr[1][i]=StoringCommShots.arr[1][i+1];
                    if(i==198){
                        StoringCommShots.arr[0][199]=null;
                        StoringCommShots.arr[1][199]=null;
                    }
                }
            }
            //after shifting get previous screenshot if available, if not get next one
            if(bkBtn.isEnabled()){
                bk();
            }else if(!bkBtn.isEnabled()&&nxtbtn.isEnabled()){
                next();
            }

            //modify total no of pages
            noOpages.setText(Integer.toString(Integer.parseInt(noOpages.getText())-1));
            
            if(noOpages.getText().equals("1")){
                bkBtn.setEnabled(false);
                nxtbtn.setEnabled(false);
            }
        }
        MainUI.shotName=MainUI.shotName-1;
        MainUI.isFileSaved=false;
    }
    
    /**update the saved comments*/
    public void saveComments(){
        StoringCommShots.arr[1][Integer.parseInt(currPage.getText())-1]=comments.getText();
        MainUI.isFileSaved=false;
    }
    
    /**get No of stored images
     @return No of images*/
    public int getNoShots(){
        StoringCommShots cs=new StoringCommShots();
        int pages=cs.imgsNum();
        noOpages.setText(Integer.toString(pages));
        pagesNO=pages;
        return pages;
    }
    
    /**Setting ICON to label*/
    public void settingIco(String resource){
        imgPreviewLbl.setIcon(new ImageIcon(new ImageIcon(resource).getImage().getScaledInstance(imgPreviewLbl.getWidth(), imgPreviewLbl.getHeight(), Image.SCALE_SMOOTH)));
    }
    
    /**opening the previous screenshot and enable/disable navigators*/
    public void bk(){
        StoringCommShots cs=new StoringCommShots();
        currPage.setText(Integer.toString(Integer.parseInt(currPage.getText())-1));
        if(nxtbtn.isEnabled()==false&&!currPage.getText().equals(Integer.toString(cs.imgsNum()))){
            nxtbtn.setEnabled(true);
        
        }
        //setting icon
        settingIco(StoringCommShots.arr[0][Integer.parseInt(currPage.getText())-1]);
        if(currPage.getText().equals("1")){
            bkBtn.setEnabled(false);
        }
        //setting comment
        comments.setText(StoringCommShots.arr[1][Integer.parseInt(currPage.getText())-1]);
    }
    /***open next screenshot and enable or disable navigator*/
    public void next(){
        StoringCommShots cs=new StoringCommShots();
         if(bkBtn.isEnabled()==false && !noOpages.getText().equals("1")){
            bkBtn.setEnabled(true);
        }
        if(!currPage.getText().equals(Integer.toString(cs.imgsNum()))){
            currPage.setText(Integer.toString(Integer.parseInt(currPage.getText())+1));  
        }
//setting icon        
        settingIco(StoringCommShots.arr[0][Integer.parseInt(currPage.getText())-1]);
        if(noOpages.getText().equals(currPage.getText())||currPage.getText().equals(Integer.toString(cs.imgsNum()))){
            nxtbtn.setEnabled(false);        
        }
        //setting comments
        comments.setText(StoringCommShots.arr[1][Integer.parseInt(currPage.getText())-1]);
    }
    
    /**Copy and paste image in specific location
     @param imgin  IMG src
     @param  imgOut  IMG will be saved to
     @exception FileNotFoundException
     @exception  IOException*/
    public void copyPasteImg(String imgin, String imgOut){
        try {
            FileInputStream in = new FileInputStream(imgin);
            FileOutputStream ou = new FileOutputStream(imgOut);
            BufferedInputStream bin = new BufferedInputStream(in);
            BufferedOutputStream bou = new BufferedOutputStream(ou);
            int b=0;
            while(b!=-1){
                b=bin.read();
                bou.write(b);
            }
            bin.close();
            bou.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ImgView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ImgView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImgView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImgView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImgView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImgView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImgView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bkBtn;
    private javax.swing.JTextArea comments;
    private javax.swing.JLabel currPage;
    private javax.swing.JButton delBtn;
    private javax.swing.JLabel imgPreviewLbl;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel noOpages;
    private javax.swing.JButton nxtbtn;
    private javax.swing.JButton saveAsbtn;
    // End of variables declaration//GEN-END:variables
}
