/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imageViewer;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.WindowEvent;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import recordscreenshot.StoringCommShots;
import frames.MainUI;
/**
 *
 * @author Salah
 */
public class ImgView extends javax.swing.JFrame {

    int pagesNO;
    /**
     * Creates new form ImgView
     */
    public ImgView() {
        initComponents();
        if(getNoShots()==0){
            JOptionPane.showConfirmDialog(null, "There're no added images to preview");
            WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
            Toolkit.getDefaultToolkit().getSystemEve­ntQueue().postEvent(winClosingEvent);
            
        }else{
//            System.out.println("label size:"+imgPreviewLbl.getSize());
//            imgPreviewLbl.setSize(1365, 598);
//            1365 x 598

            settingIco(StoringCommShots.arr[0][0]);
            comments.setText(StoringCommShots.arr[1][0]);
//            imgPreviewLbl.setIcon(new ImageIcon(StoringCommShots.arr[0][0]));
//            imgPreviewLbl.setHorizontalAlignment(imgPreviewLbl.CENTER);
//            System.out.println(imgPreviewLbl.getSize());
            currPage.setText("1");
        }
        
        if(noOpages.getText().equals(currPage.getText())){
            nxtbtn.setEnabled(false);        
        }
        bkBtn.setEnabled(false);
        StoringCommShots cs=new StoringCommShots();
        System.out.println("------");
        cs.displayArr();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        imgPreviewLbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        nxtbtn = new javax.swing.JButton();
        bkBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        noOpages = new javax.swing.JLabel();
        currPage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        comments = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1265, 603));
        setResizable(false);

        jButton1.setText("Save as");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        nxtbtn.setText(">");
        nxtbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxtbtnActionPerformed(evt);
            }
        });

        bkBtn.setText("<");
        bkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkBtnActionPerformed(evt);
            }
        });

        delBtn.setText("Delete");
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        noOpages.setText("jLabel2");

        currPage.setText("jLabel1");

        jLabel1.setText("of");

        comments.setColumns(20);
        comments.setRows(5);
        jScrollPane2.setViewportView(comments);

        jLabel2.setText("Comments");

        jButton2.setText("update comments");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(imgPreviewLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(bkBtn)
                        .addGap(36, 36, 36)
                        .addComponent(nxtbtn)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(currPage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(noOpages))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 412, Short.MAX_VALUE)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jButton1)
                        .addGap(137, 137, 137)
                        .addComponent(delBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(75, 75, 75)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(imgPreviewLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bkBtn)
                            .addComponent(nxtbtn)
                            .addComponent(noOpages)
                            .addComponent(currPage)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(delBtn)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(21, 21, 21)
                                .addComponent(jButton2))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50))
        );

        jScrollPane1.setViewportView(jPanel1);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1049, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nxtbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxtbtnActionPerformed
        // TODO add your handling code here:
        next();
    }//GEN-LAST:event_nxtbtnActionPerformed

    private void bkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkBtnActionPerformed
        // TODO add your handling code here:
        bk();
        
    }//GEN-LAST:event_bkBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        // TODO add your handling code here:
        StoringCommShots cs=new StoringCommShots();
        File img=new File(StoringCommShots.arr[0][Integer.parseInt(currPage.getText())-1]);
        if(noOpages.getText().equals("1")){
            WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
            Toolkit.getDefaultToolkit().getSystemEve­ntQueue().postEvent(winClosingEvent);
            img.delete();
            StoringCommShots.arr[0][0]=null;
            StoringCommShots.arr[1][0]=null;
            
        }else{
            img.delete();
            //shifting array after delete

            int currPageindex=Integer.parseInt(currPage.getText())-1;
            int lastIndex=cs.getLastIndex();
            
            if(currPageindex==lastIndex){
                StoringCommShots.arr[0][lastIndex]=null;
                StoringCommShots.arr[1][lastIndex]=null;
            }else{
                for(int i=Integer.parseInt(currPage.getText())-1;i<4;i++){
                    StoringCommShots.arr[0][i]=StoringCommShots.arr[0][i+1];
                    StoringCommShots.arr[1][i]=StoringCommShots.arr[1][i+1];
                    if(i==3){
                        StoringCommShots.arr[0][4]=null;
                        StoringCommShots.arr[1][4]=null;
                    }
                }
            }
            
            //open the previous image
    //        settingIco(StoringCommShots.arr[0][Integer.parseInt(currPage.getText())-2]);
            if(bkBtn.isEnabled()){
                bk();
            }else if(!bkBtn.isEnabled()&&nxtbtn.isEnabled()){
                next();
            }

            //modify total no of pages
            noOpages.setText(Integer.toString(Integer.parseInt(noOpages.getText())-1));
            
            if(noOpages.getText().equals("1")){
                bkBtn.setEnabled(false);
                nxtbtn.setEnabled(false);
            }
        }
        MainUI.shotName=MainUI.shotName-1;

        
    }//GEN-LAST:event_delBtnActionPerformed
/**
 * jLabel1.setIcon(new ImageIcon("C:\\Users\\Salah\\Downloads\\51IEqZXGe0L._AC_.jpg"));
        jLabel1.setHorizontalAlignment(jLabel1.CENTER);
 */
    
    public int getNoShots(){
        StoringCommShots cs=new StoringCommShots();

        int pages=cs.imgsNum();
        noOpages.setText(Integer.toString(pages));
        pagesNO=pages;
        return pages;
    }
    
    public void settingIco(String resource){
        imgPreviewLbl.setIcon(new ImageIcon(new ImageIcon(resource).getImage().getScaledInstance(imgPreviewLbl.getWidth(), imgPreviewLbl.getHeight(), Image.SCALE_SMOOTH)));
    }
    
    public void bk(){
        StoringCommShots cs=new StoringCommShots();
        currPage.setText(Integer.toString(Integer.parseInt(currPage.getText())-1));
        if(nxtbtn.isEnabled()==false&&!currPage.getText().equals(Integer.toString(cs.imgsNum()))){
            nxtbtn.setEnabled(true);
        
        }
        
//        imgPreviewLbl.setIcon(new ImageIcon(StoringCommShots.arr[0][Integer.parseInt(currPage.getText())-1]));
        settingIco(StoringCommShots.arr[0][Integer.parseInt(currPage.getText())-1]);
        if(currPage.getText().equals("1")){
            bkBtn.setEnabled(false);
        }
         comments.setText(StoringCommShots.arr[1][Integer.parseInt(currPage.getText())-1]);
    }
    
    public void next(){
        System.out.println("label size:"+imgPreviewLbl.getSize());
        StoringCommShots cs=new StoringCommShots();
         if(bkBtn.isEnabled()==false && !noOpages.getText().equals("1")){
            bkBtn.setEnabled(true);
        }
//        imgPreviewLbl.setIcon(new ImageIcon(StoringCommShots.arr[0][Integer.parseInt(currPage.getText())]));
        if(!currPage.getText().equals(Integer.toString(cs.imgsNum()))){
            currPage.setText(Integer.toString(Integer.parseInt(currPage.getText())+1));  
        }        
        settingIco(StoringCommShots.arr[0][Integer.parseInt(currPage.getText())-1]);
        if(noOpages.getText().equals(currPage.getText())||currPage.getText().equals(Integer.toString(cs.imgsNum()))){
            nxtbtn.setEnabled(false);        
        }
        comments.setText(StoringCommShots.arr[1][Integer.parseInt(currPage.getText())-1]);
    }
    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImgView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImgView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImgView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImgView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImgView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bkBtn;
    private javax.swing.JTextArea comments;
    private javax.swing.JLabel currPage;
    private javax.swing.JButton delBtn;
    private javax.swing.JLabel imgPreviewLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel noOpages;
    private javax.swing.JButton nxtbtn;
    // End of variables declaration//GEN-END:variables
}
